spring:
  thymeleaf:
    cache:false
  datasource:
    url: jdbc:mysql://xxx:3306/neuseer
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    type-aliases-package: com.xidian.neuseer.domain
  server:
    port: 8080